repos:
 -  repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-docstring-first
      - id: debug-statements
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
 -  repo: https://github.com/asottile/reorder-python-imports
    rev: v3.14.0
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus]
 -  repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
 -  repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
        files: ^(DefuseZip/)|^(tests/)
 -  repo: https://github.com/asottile/dead
    rev: v2.1.0
    hooks:
    -   id: dead
 -  repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
    -   id: forbid-crlf
    -   id: remove-crlf
 -  repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.6
    hooks:
    -   id: python-bandit-vulnerability-check
        args: ["--exclude ./.tox/*,./tests/*"]
 -  repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3
        types: [ python ]
        files: ^(DefuseZip/)|^(tests/)
 -  repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        name: flake8
        types: [ python ]
        files: ^(DefuseZip/)|^(tests/)
